name: Epicgames Freebies Claimer
on: 
  push:
  workflow_dispatch:
  repository_dispatch:
  schedule:
    - cron:  '42 16 * * *'
  watch:
    types: [started]

jobs:
  Claim:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: "Revadike/epicgames-freebies-claimer"
          persist-credentials: false
      - name: Use Node.js 14.x 
        uses: actions/setup-node@v2 
        with:
          node-version: "14.x"
                  
      - name: Run
        env:
          AUTH_JSON: ${{ secrets.AUTH_JSON }}
          CONFIG: ${{ secrets.CONFIG }}
        run: |
          echo "$AUTH_JSON" | tr -d '\r' > $GITHUB_WORKSPACE/data/device_auths.json
          echo "$CONFIG" | tr -d '\r' > $GITHUB_WORKSPACE/data/config.json
          npm install
          npm start
